name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Plugin ZIP
        run: |
          mkdir enix-updater
          # Copy everything into a folder named enix-updater, excluding git files
          rsync -rr --exclude='.git/' --exclude='.github/' --exclude='enix-updater' ./ enix-updater/
          zip -r enix-updater.zip enix-updater/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: enix-updater.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
